In [21]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [28]:
import zipfile

with zipfile.ZipFile('/Users/rui/Downloads/F-F_Research_Data_Factors_weekly_CSV.zip', 'r') as z:
    z.extractall('/Users/rui/Downloads/ff_data')

In [362]:
import pandas as pd

factor_df = pd.read_csv(
    '/Users/rui/Downloads/ff_data/F-F_Research_Data_Factors_weekly.csv',
    skiprows=4
)
factor_df = factor_df.rename(columns={factor_df.columns[0]: "Date"})
factor_df["Date"] = pd.to_datetime(factor_df["Date"], errors="coerce")
factor_df = factor_df.dropna(subset=["Date"])
factor_df = factor_df[(factor_df['Date'] >= '2020-01-01') &
                    (factor_df['Date'] <= '2025-03-09')]

factor_df

           Date  Mkt-RF   SMB   HML    RF
4878 2020-01-03   -0.12 -0.31  0.35  0.03
4879 2020-01-10    0.94 -0.96 -2.27  0.03
4880 2020-01-17    2.00  0.63 -1.34  0.03
4881 2020-01-24   -1.14 -1.26 -1.03  0.03
4882 2020-01-31   -2.06 -1.09 -1.45  0.03
...         ...     ...   ...   ...   ...
5144 2025-02-07   -0.36 -0.23  0.47  0.08
5145 2025-02-14    1.33 -0.73 -0.15  0.08
5146 2025-02-21   -2.19 -2.29  0.79  0.08
5147 2025-02-28   -1.21 -2.68  3.86  0.08
5148 2025-03-07   -3.48 -0.06 -1.21  0.09

[271 rows x 5 columns]

In [167]:
jpm_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/JPM_1940-01-01_2025-03-04.csv')


jpm_df['date'] = pd.to_datetime(jpm_df['date'], utc=True)


jpm_df['date'] = jpm_df['date'].dt.tz_convert(None)


jpm_df = jpm_df[(jpm_df['date'] >= '2019-12-25') &
                    (jpm_df['date'] <= '2026-05-29')]


jpm_df = jpm_df.set_index('date').sort_index()


jpm_weekly_df = jpm_df.resample('W').last()
jpm_weekly_df['return'] = jpm_weekly_df['close'].pct_change()
jpm_weekly_df=jpm_weekly_df.dropna()
jpm_weekly_df['return']

date
2020-01-05   -0.005750
2020-01-12   -0.016409
2020-01-19    0.015654
2020-01-26   -0.036541
2020-02-02   -0.005933
                ...
2025-02-09    0.031799
2025-02-16    0.002864
2025-02-23   -0.044651
2025-03-02    0.001552
2025-03-09   -0.015228
Freq: W-SUN, Name: return, Length: 271, dtype: float64

In [168]:
msft_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/MSFT_Stock_Data_1986_2026.csv')


msft_df['Date'] = pd.to_datetime(msft_df['Date'], utc=True)


msft_df['Date'] = msft_df['Date'].dt.tz_convert(None)


msft_df = msft_df[(msft_df['Date'] >= '2019-12-25') &
                    (msft_df['Date'] <= '2025-03-09')]


msft_df = msft_df.set_index('Date').sort_index()


msft_weekly_df = msft_df.resample('W').last()
msft_weekly_df['return'] = msft_weekly_df['Close'].pct_change()
msft_weekly_df=msft_weekly_df.dropna()
msft_weekly_df['return']

Date
2020-01-05   -0.002138
2020-01-12    0.017147
2020-01-19    0.035701
2020-01-26   -0.012327
2020-02-02    0.031446
                ...
2025-02-09   -0.012793
2025-02-16   -0.003221
2025-02-23    0.001465
2025-03-02   -0.027486
2025-03-09   -0.009270
Freq: W-SUN, Name: return, Length: 271, dtype: float64

In [179]:
factor_df = factor_df.reset_index(drop=True)

In [180]:

factor_df['Date'] = pd.to_datetime(factor_df['Date'])
factor_df = factor_df.set_index('Date')

In [182]:
factor_df.index = factor_df.index + pd.Timedelta(days=2)

In [184]:
factor_df

            Mkt-RF   SMB   HML    RF
Date
2020-01-05   -0.12 -0.31  0.35  0.03
2020-01-12    0.94 -0.96 -2.27  0.03
2020-01-19    2.00  0.63 -1.34  0.03
2020-01-26   -1.14 -1.26 -1.03  0.03
2020-02-02   -2.06 -1.09 -1.45  0.03
...            ...   ...   ...   ...
2025-02-09   -0.36 -0.23  0.47  0.08
2025-02-16    1.33 -0.73 -0.15  0.08
2025-02-23   -2.19 -2.29  0.79  0.08
2025-03-02   -1.21 -2.68  3.86  0.08
2025-03-09   -3.48 -0.06 -1.21  0.09

[271 rows x 4 columns]

In [190]:
brk_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/archive (9)/BRK-B_1996-05-09_2025-08-13.csv')
brk_df['date'] = pd.to_datetime(brk_df['date'], utc=True)
brk_df['date'] = brk_df['date'].dt.tz_convert(None)
brk_df = brk_df[(brk_df['date'] >= '2019-12-25') &
                (brk_df['date'] <= '2025-03-09')]
brk_df['close'] = pd.to_numeric(brk_df['close'], errors='coerce')
brk_df = brk_df.set_index('date').sort_index()
brk_weekly_df = brk_df.resample('W').last()
brk_weekly_df['return'] = brk_weekly_df['close'].pct_change()
brk_weekly_df = brk_weekly_df.dropna()
brk_weekly_df=brk_weekly_df.dropna()
brk_weekly_df['return']

date
2020-01-05    0.000177
2020-01-12    0.001945
2020-01-19    0.015797
2020-01-26   -0.014509
2020-02-02   -0.010711
                ...
2025-02-09    0.008684
2025-02-16    0.014490
2025-02-23   -0.001772
2025-03-02    0.073297
2025-03-09   -0.035440
Freq: W-SUN, Name: return, Length: 271, dtype: float64

In [191]:
apple_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/archive (11)/aapl_stock_prices.csv')
apple_df['Date'] = pd.to_datetime(apple_df['Date'], utc=True)


apple_df['Date'] = apple_df['Date'].dt.tz_convert(None)


apple_df = apple_df[(apple_df['Date'] >= '2019-12-25') &
                    (apple_df['Date'] <= '2025-03-09')]


apple_df = apple_df.set_index('Date').sort_index()


apple_weekly_df = apple_df.resample('W').last()
apple_weekly_df['return'] = apple_weekly_df['Close'].pct_change()
apple_weekly_df=apple_weekly_df.dropna()
apple_weekly_df['return']

Date
2020-01-05    0.026329
2020-01-12    0.043371
2020-01-19    0.027068
2020-01-26   -0.001318
2020-02-02   -0.027646
                ...
2025-02-09   -0.035466
2025-02-16    0.075732
2025-02-23    0.003884
2025-03-02   -0.015109
2025-03-09   -0.011454
Freq: W-SUN, Name: return, Length: 271, dtype: float64

In [192]:
tsl_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/TSLA_stock_history.csv')
tsl_df['Date'] = pd.to_datetime(tsl_df['Date'], utc=True)


tsl_df['Date'] = tsl_df['Date'].dt.tz_convert(None)


tsl_df = tsl_df[(tsl_df['Date'] >= '2019-12-25') &
                    (tsl_df['Date'] <= '2025-03-09')]


tsl_df = tsl_df.set_index('Date').sort_index()


tsl_weekly_df = tsl_df.resample('W').last()
tsl_weekly_df['return'] = tsl_weekly_df['Close'].pct_change()
tsl_weekly_df=tsl_weekly_df.dropna()
tsl_weekly_df['return']

Date
2020-01-05    0.029346
2020-01-12    0.079321
2020-01-19    0.067657
2020-01-26    0.106406
2020-02-02    0.151818
                ...
2025-02-09   -0.106228
2025-02-16   -0.015984
2025-02-23   -0.050697
2025-03-02   -0.132682
2025-03-09   -0.103454
Freq: W-SUN, Name: return, Length: 271, dtype: float64

In [193]:
aapl = apple_weekly_df['return'].rename("APPLE")
msft = msft_weekly_df['return'].rename("MSFT")
tsl = tsl_weekly_df['return'].rename("TSLA")
brk = brk_weekly_df['return'].rename("BRK")
jpm = jpm_weekly_df['return'].rename("JPM")

In [194]:
df = pd.concat([aapl, msft, tsl, brk, jpm], axis=1)
df

               APPLE      MSFT      TSLA       BRK       JPM
2020-01-05  0.026329 -0.002138  0.029346  0.000177 -0.005750
2020-01-12  0.043371  0.017147  0.079321  0.001945 -0.016409
2020-01-19  0.027068  0.035701  0.067657  0.015797  0.015654
2020-01-26 -0.001318 -0.012327  0.106406 -0.014509 -0.036541
2020-02-02 -0.027646  0.031446  0.151818 -0.010711 -0.005933
...              ...       ...       ...       ...       ...
2025-02-09 -0.035466 -0.012793 -0.106228  0.008684  0.031799
2025-02-16  0.075732 -0.003221 -0.015984  0.014490  0.002864
2025-02-23  0.003884  0.001465 -0.050697 -0.001772 -0.044651
2025-03-02 -0.015109 -0.027486 -0.132682  0.073297  0.001552
2025-03-09 -0.011454 -0.009270 -0.103454 -0.035440 -0.015228

[271 rows x 5 columns]

In [308]:
import statsmodels.api as sm
factor_df[['Mkt-RF','SMB','HML','RF']]/= 100
excess_return = df.sub(factor_df['RF'], axis=0)
factor_df

            Mkt-RF     SMB     HML      RF
Date
2020-01-05 -0.0012 -0.0031  0.0035  0.0003
2020-01-12  0.0094 -0.0096 -0.0227  0.0003
2020-01-19  0.0200  0.0063 -0.0134  0.0003
2020-01-26 -0.0114 -0.0126 -0.0103  0.0003
2020-02-02 -0.0206 -0.0109 -0.0145  0.0003
...            ...     ...     ...     ...
2025-02-09 -0.0036 -0.0023  0.0047  0.0008
2025-02-16  0.0133 -0.0073 -0.0015  0.0008
2025-02-23 -0.0219 -0.0229  0.0079  0.0008
2025-03-02 -0.0121 -0.0268  0.0386  0.0008
2025-03-09 -0.0348 -0.0006 -0.0121  0.0009

[271 rows x 4 columns]

In [323]:
factors = factor_df[['Mkt-RF','SMB','HML']].copy()
factors

            Mkt-RF     SMB     HML
Date
2020-01-05 -0.0012 -0.0031  0.0035
2020-01-12  0.0094 -0.0096 -0.0227
2020-01-19  0.0200  0.0063 -0.0134
2020-01-26 -0.0114 -0.0126 -0.0103
2020-02-02 -0.0206 -0.0109 -0.0145
...            ...     ...     ...
2025-02-09 -0.0036 -0.0023  0.0047
2025-02-16  0.0133 -0.0073 -0.0015
2025-02-23 -0.0219 -0.0229  0.0079
2025-03-02 -0.0121 -0.0268  0.0386
2025-03-09 -0.0348 -0.0006 -0.0121

[271 rows x 3 columns]

In [324]:
print(excess_return.shape)
print(factors.shape)

print(excess_return.index[:5])
print(factors.index[:5])

print(excess_return.index.dtype)
print(factors.index.dtype)

(262, 5)
(271, 3)
DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02'],
              dtype='datetime64[ns]', name='Date', freq=None)
datetime64[ns]
datetime64[ns]

In [325]:
print(excess_return.index.difference(factors.index))

DatetimeIndex([], dtype='datetime64[ns]', freq=None)

In [326]:
common_dates = excess_return.index.intersection(factors.index)

excess_return = excess_return.loc[common_dates]
factors = factors.loc[common_dates]

In [327]:
print(excess_return.index.equals(factors.index))

True

In [328]:
X = sm.add_constant(factors)

In [329]:
print(excess_return.isna().sum())

APPLE    0
MSFT     0
TSLA     0
BRK      0
JPM      0
dtype: int64

In [330]:
excess_return = excess_return.dropna()

In [331]:
factors

            Mkt-RF     SMB     HML
2020-01-05 -0.0012 -0.0031  0.0035
2020-01-12  0.0094 -0.0096 -0.0227
2020-01-19  0.0200  0.0063 -0.0134
2020-01-26 -0.0114 -0.0126 -0.0103
2020-02-02 -0.0206 -0.0109 -0.0145
...            ...     ...     ...
2025-02-09 -0.0036 -0.0023  0.0047
2025-02-16  0.0133 -0.0073 -0.0015
2025-02-23 -0.0219 -0.0229  0.0079
2025-03-02 -0.0121 -0.0268  0.0386
2025-03-09 -0.0348 -0.0006 -0.0121

[262 rows x 3 columns]

In [332]:
lm = sm.OLS(
    excess_return['APPLE'],
    X
).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  APPLE   R-squared:                       0.593
Model:                            OLS   Adj. R-squared:                  0.588
Method:                 Least Squares   F-statistic:                     125.2
Date:                Fri, 03 Jul 2026   Prob (F-statistic):           4.57e-50
Time:                        11:48:32   Log-Likelihood:                 590.02
No. Observations:                 262   AIC:                            -1172.
Df Residuals:                     258   BIC:                            -1158.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0021      0.002      1.325      0.186      -0.001       0.005
Mkt-RF         1.0786      0.060     18.104      0.000       0.961       1.196
SMB           -0.4670      0.100     -4.662      0.000      -0.664      -0.270
HML           -0.3679      0.062     -5.957      0.000      -0.490      -0.246
==============================================================================
Omnibus:                       19.986   Durbin-Watson:                   2.012
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               33.050
Skew:                           0.462   Prob(JB):                     6.66e-08
Kurtosis:                       4.475   Cond. No.                         64.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [333]:
lm = sm.OLS(
    excess_return['JPM'],
    X
).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    JPM   R-squared:                       0.725
Model:                            OLS   Adj. R-squared:                  0.721
Method:                 Least Squares   F-statistic:                     226.2
Date:                Fri, 03 Jul 2026   Prob (F-statistic):           6.33e-72
Time:                        11:48:58   Log-Likelihood:                 638.39
No. Observations:                 262   AIC:                            -1269.
Df Residuals:                     258   BIC:                            -1254.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0004      0.001      0.274      0.784      -0.002       0.003
Mkt-RF         1.0571      0.050     21.339      0.000       0.960       1.155
SMB           -0.0634      0.083     -0.762      0.447      -0.227       0.101
HML            0.7797      0.051     15.183      0.000       0.679       0.881
==============================================================================
Omnibus:                       20.128   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               70.861
Skew:                          -0.020   Prob(JB):                     4.10e-16
Kurtosis:                       5.547   Cond. No.                         64.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [334]:
lm = sm.OLS(
    excess_return['MSFT'],
    X
).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   MSFT   R-squared:                       0.709
Model:                            OLS   Adj. R-squared:                  0.705
Method:                 Least Squares   F-statistic:                     209.2
Date:                Fri, 03 Jul 2026   Prob (F-statistic):           8.77e-69
Time:                        11:49:03   Log-Likelihood:                 662.06
No. Observations:                 262   AIC:                            -1316.
Df Residuals:                     258   BIC:                            -1302.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0012      0.001      1.013      0.312      -0.001       0.004
Mkt-RF         0.9943      0.045     21.970      0.000       0.905       1.083
SMB           -0.4911      0.076     -6.456      0.000      -0.641      -0.341
HML           -0.5100      0.047    -10.869      0.000      -0.602      -0.418
==============================================================================
Omnibus:                       11.848   Durbin-Watson:                   2.076
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               23.046
Skew:                           0.177   Prob(JB):                     9.90e-06
Kurtosis:                       4.409   Cond. No.                         64.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [335]:
lm = sm.OLS(
    excess_return['TSLA'],
    X
).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   TSLA   R-squared:                       0.393
Model:                            OLS   Adj. R-squared:                  0.386
Method:                 Least Squares   F-statistic:                     55.79
Date:                Fri, 03 Jul 2026   Prob (F-statistic):           7.85e-28
Time:                        11:49:04   Log-Likelihood:                 314.58
No. Observations:                 262   AIC:                            -621.2
Df Residuals:                     258   BIC:                            -606.9
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0073      0.005      1.615      0.108      -0.002       0.016
Mkt-RF         1.9067      0.170     11.185      0.000       1.571       2.242
SMB            0.3430      0.287      1.197      0.232      -0.221       0.907
HML           -0.7338      0.177     -4.152      0.000      -1.082      -0.386
==============================================================================
Omnibus:                       29.820   Durbin-Watson:                   1.888
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               45.398
Skew:                           0.699   Prob(JB):                     1.39e-10
Kurtosis:                       4.485   Cond. No.                         64.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [336]:
lm = sm.OLS(
    excess_return['BRK'],
    X
).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    BRK   R-squared:                       0.710
Model:                            OLS   Adj. R-squared:                  0.706
Method:                 Least Squares   F-statistic:                     210.4
Date:                Fri, 03 Jul 2026   Prob (F-statistic):           5.21e-69
Time:                        11:49:06   Log-Likelihood:                 720.61
No. Observations:                 262   AIC:                            -1433.
Df Residuals:                     258   BIC:                            -1419.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0010      0.001      1.015      0.311      -0.001       0.003
Mkt-RF         0.7831      0.036     21.636      0.000       0.712       0.854
SMB           -0.2361      0.061     -3.881      0.000      -0.356      -0.116
HML            0.5157      0.038     13.745      0.000       0.442       0.590
==============================================================================
Omnibus:                        8.602   Durbin-Watson:                   1.892
Prob(Omnibus):                  0.014   Jarque-Bera (JB):               13.074
Skew:                           0.187   Prob(JB):                      0.00145
Kurtosis:                       4.029   Cond. No.                         64.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [337]:
import pandas as pd
import statsmodels.api as sm

results = []

for stock in excess_return.columns:

    y = excess_return[stock]

    X = sm.add_constant(factors)

    model = sm.OLS(y, X).fit()

    results.append({
        'stock': stock,
        'alpha': model.params['const'],
        'mkt_beta': model.params['Mkt-RF'],
        'smb_beta': model.params['SMB'],
        'hml_beta': model.params['HML'],
        'r2': model.rsquared,
        'alpha_pvalue': model.pvalues['const']
    })

summary_df = pd.DataFrame(results)

In [338]:
summary_df

   stock     alpha  mkt_beta  smb_beta  hml_beta        r2  alpha_pvalue
0  APPLE  0.002107  1.078644 -0.466955 -0.367944  0.592814      0.186331
1   MSFT  0.001223  0.994312 -0.491133 -0.509950  0.708658      0.312173
2   TSLA  0.007348  1.906739  0.342976 -0.733824  0.393490      0.107582
3    BRK  0.000981  0.783064 -0.236125  0.515743  0.709834      0.310856
4    JPM  0.000362  1.057067 -0.063412  0.779746  0.724570      0.784328

In [340]:
value_portfolio=(excess_return['BRK']+excess_return['JPM'])/2

In [341]:
growth_portfolio=(excess_return['APPLE']+excess_return['TSLA']+excess_return['MSFT'])/3

In [343]:
value_portfolio.head()

2020-01-05   -0.003086
2020-01-12   -0.007532
2020-01-19    0.015426
2020-01-26   -0.025825
2020-02-02   -0.008622
dtype: float64

In [344]:
growth_portfolio.head()

2020-01-05    0.017545
2020-01-12    0.046313
2020-01-19    0.043175
2020-01-26    0.030620
2020-02-02    0.051573
dtype: float64

In [348]:
value_sum = (1 + value_portfolio).cumprod()

growth_sum = (1 + growth_portfolio).cumprod()

In [349]:
value_sum.tail()

2025-02-09    1.528022
2025-02-16    1.540059
2025-02-23    1.503079
2025-03-02    1.558128
2025-03-09    1.517253
dtype: float64

In [350]:
growth_sum.tail()

2025-02-09    3.884683
2025-02-16    3.954772
2025-02-23    3.891828
2025-03-02    3.661333
2025-03-09    3.506485
dtype: float64

In [353]:
import numpy as np
value_portfolio.std() * np.sqrt(52)

np.float64(0.23336166498448135)

In [354]:
growth_portfolio.std() * np.sqrt(52)

np.float64(0.3456502632067089)

In [356]:
import numpy as np
value_sharpe=(value_portfolio.mean()/value_portfolio.std())*np.sqrt(52)
value_sharpe

np.float64(0.47265297283695457)

In [358]:
growth_sharpe=(growth_portfolio.mean()/growth_portfolio.std())*np.sqrt(52)
growth_sharpe

np.float64(0.8939199601023903)

In [359]:
def max_drawdown(ret):
    cum = (1 + ret).cumprod()
    drawdown = cum / cum.cummax() - 1
    return drawdown.min()

In [360]:
value_mdd = max_drawdown(value_portfolio)

growth_mdd = max_drawdown(growth_portfolio)

print(value_mdd)
print(growth_mdd)

-0.4132111053983708
-0.45940516017028143