In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
import zipfile

with zipfile.ZipFile('/Users/rui/Downloads/F-F_Research_Data_Factors_weekly_CSV.zip', 'r') as z:
    z.extractall('/Users/rui/Downloads/ff_data')

In [3]:
import pandas as pd

factor_df = pd.read_csv(
    '/Users/rui/Downloads/ff_data/F-F_Research_Data_Factors_weekly.csv',
    skiprows=4
)
factor_df = factor_df.rename(columns={factor_df.columns[0]: "Date"})
factor_df["Date"] = pd.to_datetime(factor_df["Date"], errors="coerce")
factor_df = factor_df.dropna(subset=["Date"])
factor_df = factor_df[(factor_df['Date'] >= '2020-01-01') &
                    (factor_df['Date'] <= '2022-03-09')]

factor_df

           Date  Mkt-RF   SMB   HML    RF
4878 2020-01-03   -0.12 -0.31  0.35  0.03
4879 2020-01-10    0.94 -0.96 -2.27  0.03
4880 2020-01-17    2.00  0.63 -1.34  0.03
4881 2020-01-24   -1.14 -1.26 -1.03  0.03
4882 2020-01-31   -2.06 -1.09 -1.45  0.03
...         ...     ...   ...   ...   ...
4987 2022-02-04    2.04 -0.46  0.21  0.00
4988 2022-02-11   -1.28  1.89  1.44  0.00
4989 2022-02-18   -1.69  1.01  0.43  0.00
4990 2022-02-25    0.92  0.45 -1.26  0.00
4991 2022-03-04   -1.67 -0.26  2.27  0.00

[114 rows x 5 columns]

In [4]:
jpm_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/JPM_1940-01-01_2025-03-04.csv')


jpm_df['date'] = pd.to_datetime(jpm_df['date'], utc=True)


jpm_df['date'] = jpm_df['date'].dt.tz_convert(None)


jpm_df = jpm_df[(jpm_df['date'] >= '2019-12-25') &
                    (jpm_df['date'] <= '2022-03-09')]


jpm_df = jpm_df.set_index('date').sort_index()


jpm_weekly_df = jpm_df.resample('W').last()
jpm_weekly_df['return'] = jpm_weekly_df['close'].pct_change()
jpm_weekly_df=jpm_weekly_df.dropna()
jpm_weekly_df['return']

date
2020-01-05   -0.005750
2020-01-12   -0.016409
2020-01-19    0.015654
2020-01-26   -0.036541
2020-02-02   -0.005933
                ...
2022-02-13    0.008915
2022-02-20   -0.011564
2022-02-27   -0.027409
2022-03-06   -0.091708
2022-03-13   -0.045387
Freq: W-SUN, Name: return, Length: 115, dtype: float64

In [5]:
msft_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/MSFT_Stock_Data_1986_2026.csv')


msft_df['Date'] = pd.to_datetime(msft_df['Date'], utc=True)


msft_df['Date'] = msft_df['Date'].dt.tz_convert(None)


msft_df = msft_df[(msft_df['Date'] >= '2019-12-25') &
                    (msft_df['Date'] <= '2022-03-09')]


msft_df = msft_df.set_index('Date').sort_index()


msft_weekly_df = msft_df.resample('W').last()
msft_weekly_df['return'] = msft_weekly_df['Close'].pct_change()
msft_weekly_df=msft_weekly_df.dropna()
msft_weekly_df['return']

Date
2020-01-05   -0.002138
2020-01-12    0.017147
2020-01-19    0.035701
2020-01-26   -0.012327
2020-02-02    0.031446
                ...
2022-02-13   -0.035628
2022-02-20   -0.022081
2022-02-27    0.032577
2022-03-06   -0.025058
2022-03-13   -0.004691
Freq: W-SUN, Name: return, Length: 115, dtype: float64

In [6]:
factor_df = factor_df.reset_index(drop=True)

In [7]:
factor_df['Date'] = pd.to_datetime(factor_df['Date'])
factor_df = factor_df.set_index('Date')

In [8]:
factor_df.index = factor_df.index + pd.Timedelta(days=2)

In [9]:
factor_df

            Mkt-RF   SMB   HML    RF
Date
2020-01-05   -0.12 -0.31  0.35  0.03
2020-01-12    0.94 -0.96 -2.27  0.03
2020-01-19    2.00  0.63 -1.34  0.03
2020-01-26   -1.14 -1.26 -1.03  0.03
2020-02-02   -2.06 -1.09 -1.45  0.03
...            ...   ...   ...   ...
2022-02-06    2.04 -0.46  0.21  0.00
2022-02-13   -1.28  1.89  1.44  0.00
2022-02-20   -1.69  1.01  0.43  0.00
2022-02-27    0.92  0.45 -1.26  0.00
2022-03-06   -1.67 -0.26  2.27  0.00

[114 rows x 4 columns]

In [10]:
brk_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/archive (9)/BRK-B_1996-05-09_2025-08-13.csv')
brk_df['date'] = pd.to_datetime(brk_df['date'], utc=True)
brk_df['date'] = brk_df['date'].dt.tz_convert(None)
brk_df = brk_df[(brk_df['date'] >= '2019-12-25') &
                (brk_df['date'] <= '2022-03-09')]
brk_df['close'] = pd.to_numeric(brk_df['close'], errors='coerce')
brk_df = brk_df.set_index('date').sort_index()
brk_weekly_df = brk_df.resample('W').last()
brk_weekly_df['return'] = brk_weekly_df['close'].pct_change()
brk_weekly_df = brk_weekly_df.dropna()
brk_weekly_df=brk_weekly_df.dropna()
brk_weekly_df['return']

date
2020-01-05    0.000177
2020-01-12    0.001945
2020-01-19    0.015797
2020-01-26   -0.014509
2020-02-02   -0.010711
                ...
2022-02-13    0.013175
2022-02-20   -0.013599
2022-02-27    0.014104
2022-03-06    0.019108
2022-03-13    0.000184
Freq: W-SUN, Name: return, Length: 115, dtype: float64

In [14]:
apple_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/archive (11)/aapl_stock_prices.csv')
apple_df['Date'] = pd.to_datetime(apple_df['Date'], utc=True)


apple_df['Date'] = apple_df['Date'].dt.tz_convert(None)


apple_df = apple_df[(apple_df['Date'] >= '2019-12-25') &
                    (apple_df['Date'] <= '2022-03-09')]


apple_df = apple_df.set_index('Date').sort_index()


apple_weekly_df = apple_df.resample('W').last()
apple_weekly_df['return'] = apple_weekly_df['Close'].pct_change()
apple_weekly_df=apple_weekly_df.dropna()
apple_weekly_df['return']

Date
2020-01-05    0.026329
2020-01-12    0.043371
2020-01-19    0.027068
2020-01-26   -0.001318
2020-02-02   -0.027646
                ...
2022-02-13   -0.021753
2022-02-20   -0.007946
2022-02-27   -0.014644
2022-03-06   -0.010191
2022-03-13   -0.001348
Freq: W-SUN, Name: return, Length: 115, dtype: float64

In [13]:
tsl_df = pd.read_csv('/Users/rui/Desktop/untitled folder 2/TSLA_stock_history.csv')
tsl_df['Date'] = pd.to_datetime(tsl_df['Date'], utc=True)


tsl_df['Date'] = tsl_df['Date'].dt.tz_convert(None)


tsl_df = tsl_df[(tsl_df['Date'] >= '2019-12-25') &
                    (tsl_df['Date'] <= '2022-03-09')]


tsl_df = tsl_df.set_index('Date').sort_index()


tsl_weekly_df = tsl_df.resample('W').last()
tsl_weekly_df['return'] = tsl_weekly_df['Close'].pct_change()
tsl_weekly_df=tsl_weekly_df.dropna()
tsl_weekly_df['return']

Date
2020-01-05    0.029346
2020-01-12    0.079321
2020-01-19    0.067657
2020-01-26    0.106406
2020-02-02    0.151818
                ...
2022-02-13   -0.068579
2022-02-20   -0.003512
2022-02-27   -0.054972
2022-03-06    0.035092
2022-03-13    0.024669
Freq: W-SUN, Name: return, Length: 115, dtype: float64

In [15]:
aapl = apple_weekly_df['return'].rename("APPLE")
msft = msft_weekly_df['return'].rename("MSFT")
tsl = tsl_weekly_df['return'].rename("TSLA")
brk = brk_weekly_df['return'].rename("BRK")
jpm = jpm_weekly_df['return'].rename("JPM")

In [16]:
df = pd.concat([aapl, msft, tsl, brk, jpm], axis=1)
df

               APPLE      MSFT      TSLA       BRK       JPM
2020-01-05  0.026329 -0.002138  0.029346  0.000177 -0.005750
2020-01-12  0.043371  0.017147  0.079321  0.001945 -0.016409
2020-01-19  0.027068  0.035701  0.067657  0.015797  0.015654
2020-01-26 -0.001318 -0.012327  0.106406 -0.014509 -0.036541
2020-02-02 -0.027646  0.031446  0.151818 -0.010711 -0.005933
...              ...       ...       ...       ...       ...
2022-02-13 -0.021753 -0.035628 -0.068579  0.013175  0.008915
2022-02-20 -0.007946 -0.022081 -0.003512 -0.013599 -0.011564
2022-02-27 -0.014644  0.032577 -0.054972  0.014104 -0.027409
2022-03-06 -0.010191 -0.025058  0.035092  0.019108 -0.091708
2022-03-13 -0.001348 -0.004691  0.024669  0.000184 -0.045387

[115 rows x 5 columns]

In [17]:
import statsmodels.api as sm
factor_df[['Mkt-RF','SMB','HML','RF']]/= 100
excess_return = df.sub(factor_df['RF'], axis=0)
factor_df

            Mkt-RF     SMB     HML      RF
Date
2020-01-05 -0.0012 -0.0031  0.0035  0.0003
2020-01-12  0.0094 -0.0096 -0.0227  0.0003
2020-01-19  0.0200  0.0063 -0.0134  0.0003
2020-01-26 -0.0114 -0.0126 -0.0103  0.0003
2020-02-02 -0.0206 -0.0109 -0.0145  0.0003
...            ...     ...     ...     ...
2022-02-06  0.0204 -0.0046  0.0021  0.0000
2022-02-13 -0.0128  0.0189  0.0144  0.0000
2022-02-20 -0.0169  0.0101  0.0043  0.0000
2022-02-27  0.0092  0.0045 -0.0126  0.0000
2022-03-06 -0.0167 -0.0026  0.0227  0.0000

[114 rows x 4 columns]

In [18]:
factors = factor_df[['Mkt-RF','SMB','HML']].copy()
factors

            Mkt-RF     SMB     HML
Date
2020-01-05 -0.0012 -0.0031  0.0035
2020-01-12  0.0094 -0.0096 -0.0227
2020-01-19  0.0200  0.0063 -0.0134
2020-01-26 -0.0114 -0.0126 -0.0103
2020-02-02 -0.0206 -0.0109 -0.0145
...            ...     ...     ...
2022-02-06  0.0204 -0.0046  0.0021
2022-02-13 -0.0128  0.0189  0.0144
2022-02-20 -0.0169  0.0101  0.0043
2022-02-27  0.0092  0.0045 -0.0126
2022-03-06 -0.0167 -0.0026  0.0227

[114 rows x 3 columns]

In [30]:
print(excess_return.shape)
print(factors.shape)

print(excess_return.index[:5])
print(factors.index[:5])

print(excess_return.index.dtype)
print(factors.index.dtype)

(108, 5)
(114, 3)
DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02'],
              dtype='datetime64[ns]', freq=None)
datetime64[ns]
datetime64[ns]

In [31]:
print(excess_return.index.difference(factors.index))

DatetimeIndex([], dtype='datetime64[ns]', freq=None)

In [32]:
common_dates = excess_return.index.intersection(factors.index)

excess_return = excess_return.loc[common_dates]
factors = factors.loc[common_dates]

In [33]:
print(excess_return.index.equals(factors.index))

True

In [34]:
X = sm.add_constant(factors)

In [35]:
print(excess_return.isna().sum())

APPLE    0
MSFT     0
TSLA     0
BRK      0
JPM      0
dtype: int64

In [36]:
excess_return = excess_return.dropna()

In [37]:
lm = sm.OLS(
    excess_return['APPLE'],
    X
).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  APPLE   R-squared:                       0.664
Model:                            OLS   Adj. R-squared:                  0.655
Method:                 Least Squares   F-statistic:                     68.57
Date:                Sun, 05 Jul 2026   Prob (F-statistic):           1.52e-24
Time:                        16:34:37   Log-Likelihood:                 242.95
No. Observations:                 108   AIC:                            -477.9
Df Residuals:                     104   BIC:                            -467.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0050      0.003      1.983      0.050   -1.32e-06       0.010
Mkt-RF         1.1375      0.082     13.913      0.000       0.975       1.300
SMB           -0.6190      0.146     -4.239      0.000      -0.909      -0.329
HML           -0.3677      0.080     -4.617      0.000      -0.526      -0.210
==============================================================================
Omnibus:                       22.827   Durbin-Watson:                   1.862
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.957
Skew:                           0.941   Prob(JB):                     9.44e-09
Kurtosis:                       5.161   Cond. No.                         59.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [38]:
import pandas as pd
import statsmodels.api as sm

results = []

for stock in excess_return.columns:

    y = excess_return[stock]

    X = sm.add_constant(factors)

    model = sm.OLS(y, X).fit()

    results.append({
        'stock': stock,
        'alpha': model.params['const'],
        'mkt_beta': model.params['Mkt-RF'],
        'smb_beta': model.params['SMB'],
        'hml_beta': model.params['HML'],
        'r2': model.rsquared,
        'alpha_pvalue': model.pvalues['const']
    })

summary_df = pd.DataFrame(results)

In [39]:
summary_df

   stock     alpha  mkt_beta  smb_beta  hml_beta        r2  alpha_pvalue
0  APPLE  0.004966  1.137489 -0.618965 -0.367676  0.664196      0.050060
1   MSFT  0.003280  0.986633 -0.539007 -0.433936  0.741300      0.081823
2   TSLA  0.017238  2.042670  0.463924 -0.878382  0.476092      0.018156
3    BRK  0.001326  0.705696 -0.269720  0.552845  0.790719      0.371245
4    JPM -0.003306  0.975099 -0.075757  0.849312  0.802407      0.117329

In [40]:
value_portfolio=(excess_return['BRK']+excess_return['JPM'])/2

In [41]:
growth_portfolio=(excess_return['APPLE']+excess_return['TSLA']+excess_return['MSFT'])/3

In [42]:
value_portfolio.head()

2020-01-05   -0.003086
2020-01-12   -0.007532
2020-01-19    0.015426
2020-01-26   -0.025825
2020-02-02   -0.008622
dtype: float64

In [43]:
growth_portfolio.head()

2020-01-05    0.017545
2020-01-12    0.046313
2020-01-19    0.043175
2020-01-26    0.030620
2020-02-02    0.051573
dtype: float64

In [44]:
value_sum = (1 + value_portfolio).cumprod()

growth_sum = (1 + growth_portfolio).cumprod()

In [45]:
value_sum.tail()

2022-02-06    1.013067
2022-02-13    1.024257
2022-02-20    1.011370
2022-02-27    1.004642
2022-03-06    0.968173
dtype: float64

In [46]:
growth_sum.tail()

2022-02-06    2.856805
2022-02-13    2.736858
2022-02-20    2.706261
2022-02-27    2.672849
2022-03-06    2.672709
dtype: float64

In [47]:
import numpy as np
value_portfolio.std() * np.sqrt(52)

np.float64(0.2790216443246428)

In [48]:
growth_portfolio.std() * np.sqrt(52)

np.float64(0.3766800713481215)

In [49]:
import numpy as np
value_sharpe=(value_portfolio.mean()/value_portfolio.std())*np.sqrt(52)
value_sharpe

np.float64(0.08564866193534244)

In [50]:
growth_sharpe=(growth_portfolio.mean()/growth_portfolio.std())*np.sqrt(52)
growth_sharpe

np.float64(1.450521451250021)

In [51]:
def max_drawdown(ret):
    cum = (1 + ret).cumprod()
    drawdown = cum / cum.cummax() - 1
    return drawdown.min()

In [52]:
value_mdd = max_drawdown(value_portfolio)

growth_mdd = max_drawdown(growth_portfolio)

print(value_mdd)
print(growth_mdd)

-0.4132111053983708
-0.35000012562418725

In [53]:
avg_return = excess_return.mean()

In [54]:
cs_df = summary_df.copy()
cs_df['avg_return'] = avg_return.values

In [55]:
import statsmodels.api as sm

X = cs_df[['mkt_beta', 'smb_beta', 'hml_beta']]
X = sm.add_constant(X)

y = cs_df['avg_return']

model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             avg_return   R-squared:                       0.959
Model:                            OLS   Adj. R-squared:                  0.835
Method:                 Least Squares   F-statistic:                     7.766
Date:                Sun, 05 Jul 2026   Prob (F-statistic):              0.257
Time:                        22:21:30   Log-Likelihood:                 25.385
No. Observations:                   5   AIC:                            -42.77
Df Residuals:                       1   BIC:                            -44.33
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0092      0.018      0.523      0.693      -0.215       0.233
mkt_beta      -0.0009      0.013     -0.070      0.956      -0.172       0.170
smb_beta       0.0103      0.011      0.943      0.519      -0.128       0.149
hml_beta      -0.0091      0.006     -1.424      0.390      -0.091       0.072
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.618
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.563
Skew:                          -0.185   Prob(JB):                        0.755
Kurtosis:                       1.398   Cond. No.                         26.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.